<?php 
  global $current_page;
  $current_page = "page-news";

?>
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
  <?php include 'includes/head.php'; ?>
</head>

<body class="<?php echo $current_page; ?>">

  <?php include "includes/preloader.php"; ?>

  <?php include "includes/header_desktop.php"; ?>
  <?php include "includes/header_mobile.php"; ?>

  <div id="page-wrapper">
    <div id="page-wrapper-content">

      <div id="page-home-nav-trigger"></div>


      <div class="header-desktop-spacer"></div>
      
      <article id="page-news-featured-section">
        <div class="container-fluid has-breakpoint">

          <div id="page-news-featured-carousel" class="transmedic-slick-slider">
            <div class="page-news-featured-carousel-item">
              <div class="row">
                <div class="col-md-7 visible-xs visible-sm">
                  <div class="manic-image-container">
                    <img src="" 
                      data-image-desktop="images_cms/news/news-features-slider-img-01.png"
                      data-image-tablet="images_cms/news/news-features-slider-img-01.png"
                      data-image-mobile="images_cms/news/news-features-slider-img-01.png" alt="">
                  </div>
                  <span class="default-image-desc">Cancer cells completing cell division.</span>
                </div>
                <div class="col-md-5 left-carousel-column">
                  <div class="carousel-caption-container hover-sync-item">
                    <div class="default-copy">
                      <h4>Featured / 27 Jul 2017</h4>
                      <h2><a href="article.php" class="hover-sync">The Medical City (TMC) introduces Emprint™ Microwave Ablation (MWA)</a></h2>
                      <p>The Medical City (TMC) introduces Emprint™ Microwave Ablation (MWA), a new technology that destroys tumors using heat generated by microwave energy. The MWA machine was acquired by TMC in January 2017...</p>
                      <a href="article.php" class="plain-arrow-cta hover-sync">Read More</a>
                    </div>
                  </div>
                </div>
                <div class="col-md-7 right-carousel-column hidden-xs hidden-sm">
                  <div class="manic-image-container has-show-all">
                    <img src="" 
                      data-image-desktop="images_cms/news/news-features-slider-img-01.png"
                      data-image-tablet="images_cms/news/news-features-slider-img-01.png"
                      data-image-mobile="images_cms/news/news-features-slider-img-01.png" alt="">
                  </div>
                  <span class="default-image-desc">Cancer cells completing cell division.</span>
                </div>
              </div>
            </div>
            <div class="page-news-featured-carousel-item">
              <div class="row">
                <div class="col-md-7 visible-xs visible-sm">
                  <div class="manic-image-container">
                    <img src="" 
                      data-image-desktop="images_cms/news/news-features-slider-img-01.png"
                      data-image-tablet="images_cms/news/news-features-slider-img-01.png"
                      data-image-mobile="images_cms/news/news-features-slider-img-01.png" alt="">
                  </div>
                  <span class="default-image-desc">Cancer cells completing cell division.</span>
                </div>
                <div class="col-md-5 left-carousel-column">
                  <div class="carousel-caption-container">
                    <div class="default-copy">
                      <h4>Featured / 27 Jul 2017</h4>
                      <h2>The Medical City (TMC) introduces Emprint™ Microwave Ablation (MWA)</h2>
                      <p>The Medical City (TMC) introduces Emprint™ Microwave Ablation (MWA), a new technology that destroys tumors using heat generated by microwave energy. The MWA machine was acquired by TMC in January 2017...</p>
                      <a href="article.php" class="plain-arrow-cta hover-sync">Read More</a>
                    </div>
                  </div>
                </div>
                <div class="col-md-7 right-carousel-column hidden-sm hidden-xs">
                  <div class="manic-image-container has-show-all">
                    <img src="" 
                      data-image-desktop="images_cms/news/news-features-slider-img-01.png"
                      data-image-tablet="images_cms/news/news-features-slider-img-01.png"
                      data-image-mobile="images_cms/news/news-features-slider-img-01.png" alt="">
                  </div>
                  <span class="default-image-desc">Cancer cells completing cell division.</span>
                </div>
              </div>
            </div>
            <div class="page-news-featured-carousel-item">
              <div class="row">
                <div class="col-md-7 visible-xs visible-sm">
                  <div class="manic-image-container">
                    <img src="" 
                      data-image-desktop="images_cms/news/news-features-slider-img-01.png"
                      data-image-tablet="images_cms/news/news-features-slider-img-01.png"
                      data-image-mobile="images_cms/news/news-features-slider-img-01.png" alt="">
                  </div>
                  <span class="default-image-desc">Cancer cells completing cell division.</span>
                </div>
                <div class="col-md-5 left-carousel-column">
                  <div class="carousel-caption-container">
                    <div class="default-copy">
                      <h4>Featured / 27 Jul 2017</h4>
                      <h2>The Medical City (TMC) introduces Emprint™ Microwave Ablation (MWA)</h2>
                      <p>The Medical City (TMC) introduces Emprint™ Microwave Ablation (MWA), a new technology that destroys tumors using heat generated by microwave energy. The MWA machine was acquired by TMC in January 2017...</p>
                      <a href="article.php" class="plain-arrow-cta hover-sync">Read More</a>
                    </div>
                  </div>
                </div>
                <div class="col-md-7 right-carousel-column hidden-sm hidden-xs">
                  <div class="manic-image-container">
                    <img src="" 
                      data-image-desktop="images_cms/news/news-features-slider-img-01.png"
                      data-image-tablet="images_cms/news/news-features-slider-img-01.png"
                      data-image-mobile="images_cms/news/news-features-slider-img-01.png" alt="">
                  </div>
                  <span class="default-image-desc">Cancer cells completing cell division.</span>
                </div>
              </div>
            </div>
          </div>

        </div>
      </article> <!-- page-news-featured-section -->

      <article id="page-news-filter-section">
        <div class="container-fluid has-breakpoint">
            <div class="row">
              <div class="col-md-12">
                <ul id="page-news-filter-list">
                  <li><a href="#all" class="active-cat"><h3>All Categories</h3></a></li>
                  <li><a href="#featured"><h3>Featured</h3></a></li>
                  <li><a href="#latest"><h3>Latest Products</h3></a></li>
                  <li><a href="#education"><h3>Education & Events</h3></a></li>
                  <li><a href="#success"><h3>Success Stories</h3></a></li>
                  <li><a href="#life"><h3>Life at Transmedic</h3></a></li>
                </ul>
              </div>
            </div> <!-- row -->

            <div id="page-default-news-item-container" class="news-page-version">

              <!-- JS CONTENT -->

            </div> <!-- page-news-filtered-news-item-container -->

            <div id="page-news-load-more-cta-container">
              <a href="#" class="square-cta">Load More</a>
            </div>

        </div>
      </article> <!-- page-news-filtered-news-section -->
      

    </div> <!-- #page-wrapper-content -->
  </div> <!-- #page-wrapper -->

  <?php include "includes/footer_desktop.php"; ?>
  <?php include "includes/footer_mobile.php"; ?>

  <?php include "includes/script_new.php" ?>

  <script id="news-template" type="text/x-handlebars-template">
    <div class="col-md-4">
      <div class="item-column" data-news-type="all,{{ tag }}">

        <div class="page-default-news-item">
          <div class="item-title">
            <div class="row">
              <div class="col-xs-8">
                <h4>{{ category }}</h4>
              </div>
              <div class="col-xs-4">
                <h4 class="item-date">{{ date }}</h4>
              </div>
            </div>
            <h3><a href="{{ link }}" class="hover-sync minimize-text" data-length="60" data-tablet-length="25">{{ title }}</a></h3>
          </div>                      
        </div> <!-- page-default-news-item -->

      </div> <!-- item-column -->
    </div> <!-- col-md-4 -->
  </script>

</body>
</html>